%% This script is used to train and test the neural network
% written in March 2025
% Drakeson Hu

%% Prepares Training Data

% Assigns data to a datastore object
folderName = "PDAugmented2";
imds = imageDatastore(folderName, ...
    IncludeSubfolders=true, ...
    LabelSource="foldernames");

% Splits data into training, validation, and testing pools
imageAugmenter = imageDataAugmenter( ...
    'RandRotation',[-20,20], ...
    'RandXTranslation',[-10 10], ...
    'RandYTranslation',[-10 10], ...
    'RandXReflection',true);

% Creates augmentedImageDatastore objects from data; 
% normalizes array sizes, creates random cariations within the dataset
[imdsTrain,imdsValid,imdsTest] = splitEachLabel(imds,0.90,0.05,0.05,"randomized");
augimdsTrain = augmentedImageDatastore([224 224], imdsTrain, "ColorPreprocessing","gray2rgb", "DispatchInBackground", true, 'DataAugmentation', imageAugmenter);
augimdsValid = augmentedImageDatastore([224 224], imdsValid, "ColorPreprocessing","gray2rgb");
augimdsTest = augmentedImageDatastore([224 224], imdsTest, "ColorPreprocessing","gray2rgb");

% Displays Sample Images (For Testing)
numImages = numel(augimdsTrain.Files);
idx = randperm(numImages,16);
I = imtile(augimdsTrain.Files,Frames=idx);
figure
imshow(I)
%% Loads Pretrained Neural Network for Transfer Learning, Sets Hyperparameters and Executes Training

augimdsTrain.MiniBatchSize = 80;
% load net_2.mat
options = trainingOptions("sgdm", ...
    LearnRateSchedule="cosine", ...
    ValidationData=augimdsValid, ...
    ValidationFrequency=5, ...
    Plots="training-progress", ...
    Metrics=["accuracy","precision"], ...
    Shuffle="every-epoch", ...
    L2Regularization=0.0025, ...
    ObjectiveMetricName="precision", ...
    OutputNetwork="best-validation", ...
    Verbose=false, ...
    PreprocessingEnvironment="parallel", ...
    ExecutionEnvironment = 'gpu', ...
    MiniBatchSize=80, ...
    MaxEpochs=30);
trainednet = trainnet(augimdsTrain, net_1,"crossentropy",options);

%% Visualizes accuracy (For Testing)

classNames = categories(imds.Labels);

YTest1 = minibatchpredict(trainednet,augimdsTest);
YTest1 = scores2label(YTest1,classNames);

TTest = imdsTest.Labels;
figure
confusionchart(TTest,YTest1);
